### PR TITLE
Initial Project Scaffold

### PR DESCRIPTION
**Pull request by RedhatPH8**

### CODE REVIEW

**Comment by av-jones** [comment]
Checked out locally. Had build error on my end, will troubleshoot further.
image

**Comment by RedhatPH8** [comment]
Looks like it may be an angular version dependency error. I'll check it out
on my end.

**Comment by RedhatPH8** [comment]
Got it to work, had to download node v10.9 (I used this page for a multiversion tool https://docs.microsoft.com/en-us/windows/nodejs/setup-on-windows)
Once downloaded I ran powershell as administrator then
`dotnet restore` in .\UNF-EngOfSoftware2-2020.github.io\SOMA\soma\dal
`dotnet restore` in .\UNF-EngOfSoftware2-2020.github.io\SOMA\soma\soma
`npm install` in .\UNF-EngOfSoftware2-2020.github.io\SOMA\soma\soma\ClientApp\

I'm not sure why the autoload didnt compile these but it worked for me.

**Comment by RedhatPH8** [comment]
@UNF-EngOfSoftware2-2020/all-users Has anyone been able to build this?

**Comment by av-jones** [comment]
Got it running. In addition to installing Node.js 10.9.0, I had to open up the package.json file and change the start value under scripts to “ng serve” and bingo.
Screenshot 2020-03-09 16 03 10
Screenshot 2020-03-09 16 03 02
Screenshot 2020-03-09 16 00 37

**Review by av-jones — APPROVED** [review]
Got it running. In addition to installing Node.js 10.9.0, I had to open up the package.json file and change the start value under scripts to “ng serve” and bingo.

**Pull request merged**
